apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: java-springboot-hybjegvj
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/java-springboot-hybjegvj:b1fa5fddaca36312759e8af3a5b9432ef15eccbe@sha256:2a30aade41c9c939044090533e9afa740d1dcd9c834fd35b23ebbd4bd24673f5
        name: container-image  
